version: '3.4'

services:

  ocelot.api.gateway:
    container_name: ocelot.api.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "7000:80"

  catalog.api:
    container_name: catalog.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalog.db:27017"
    depends_on: 
      - catalog.db
    volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports: 
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basket.db:6379"
      - "EventBus:Hostname=rabbitmq"
    depends_on: 
      - basket.db
      - rabbitmq
    volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports: 
      - "8001:80"

  ordering.api:
    container_name: ordering.api
    restart: on-failure
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConn=server=ordering.db;Database=OrdersDB;user id=sa;password=Pass123!"
      - "EventBus:Hostname=rabbitmq"
    depends_on: 
      - ordering.db
      - rabbitmq
    volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports: 
      - "8002:80"


  ordering.db:
    container_name: ordering.db
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  catalog.db:
    container_name: catalog.db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"


