version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile

  ordering.db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  catalog.db:
    image: mongo

  basket.db:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management



