version: '3.4'

services:
  catalog.db:
    container_name: catalog.db
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalog.db:27017"
    depends_on: 
      - catalog.db
    volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports: 
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basket.db:6379"
      - "EventBus:Hostname=rabbitmq"
    depends_on: 
      - basket.db
      - rabbitmq
    volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports: 
      - "8001:80"